name: Deploy Docker Container
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get latest commit hash
        id: commit
        run: echo "::set-output name=hash::$(git rev-parse --short HEAD)"

      - name: Push to Docker Hub with latest commit tag
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: kammana/wsapp:${{ steps.commit.outputs.hash }}
        
      - name: Run Docker container on remote host
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOST_IP }}
          username: ${{ secrets.DEV_SSH_USER }}
          key: ${{ secrets.DEV_SSH_KEY }}
          script: |
            docker rm -f wsapp 2> /dev/null || true
            docker pull kammana/wsapp:${{ steps.commit.outputs.hash }}
            docker run -d --name wsapp -p 8080:8080 kammana/wsapp:${{ steps.commit.outputs.hash }}
